### PR TITLE
Adele Flash jump & clp routine

### PR DESCRIPTION
**Pull request by Nekololizu**

### CODE REVIEW

**Review by tanjeffreyz — CHANGES_REQUESTED** [review]
Thanks! Regarding the key names, yes they should just be whatever shows up in the keybind settings page. So "pageup" should instead be "page up", and "lshift" was changed to just "shift". I've just updated the main bot with this.

**Comment by Nekololizu** [comment]
Think the files should be fine now after the branch merge ?

**Comment by Nekololizu** [comment]
Guess it still dislike some keys
```
##################
#    ENABLED     #
##################
Invalid keyboard input: 'pgdn'.
Invalid keyboard input: 'pgdn'.
Invalid keyboard input: 'pgdn'.
Invalid keyboard input: 'pgdn'.
Invalid keyboard input: 'page up'.
Invalid keyboard input: 'page up'.
Invalid keyboard input: 'page up'.
Invalid keyboard input: 'page up'.
```
^this is what showed up when i tried to use the auto maple controls keybinds, so its probly something different from those


and writing them normally breaks as well
```
##################
#    ENABLED     #
##################
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pagedown'.
Invalid keyboard input: 'pageup'.
Invalid keyboard input: 'pageup'.
Invalid keyboard input: 'pageup'.
Invalid keyboard input: 'pageup'.
```

**Comment by tanjeffreyz** [comment]
Ahhh sorry about that, I somehow didn't push the pgup/pgdn changes. I've updated the [v2.3.3 release](https://github.com/tanjeffreyz/auto-maple/releases/tag/v2.3.3), so please download that again

**Comment by Nekololizu** [comment]
Looks like all invalid key presses are fixed
```
##################
#    ENABLED     #
##################



[~] Loading routine 'clp.csv':
 !  Line 27: Command 'flashjump' does not exist.
 -  Found existing Layout file at 'resources\layouts\adele\clp'.
 ~  Finished loading routine 'clp'.

[!] Cannot use 'Record position' while Auto Maple is enabled



[~] Loading routine 'clp.csv':
 !  Line 27: Command 'flashjump' does not exist.
 -  Found existing Layout file at 'resources\layouts\adele\clp'.
 ~  Finished loading routine 'clp'.



[~] Loading routine 'clp.csv':
 !  Line 27: Command 'flashjump' does not exist.
 -  Found existing Layout file at 'resources\layouts\adele\clp'.
 ~  Finished loading routine 'clp'.

[!] Cannot use 'Record position' while Auto Maple is enabled



[~] Loading routine 'clp.csv':
 !  Line 27: Command 'flashjump' does not exist.
 -  Found existing Layout file at 'resources\layouts\adele\clp'.
 ~  Finished loading routine 'clp'.



[~] Loading routine 'clp.csv':
 !  Line 27: Command 'flashjump' does not exist.
 -  Found existing Layout file at 'resources\layouts\adele\clp'.
 ~  Finished loading routine 'clp'.

[!] Cannot use 'Record position' while Auto Maple is enabled



##################
#    DISABLED    #
##################
```

**Review by tanjeffreyz — APPROVED** [review]

**Pull request merged**
